# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(choices=[('u', 'unknown'), ('h', 'hygrometry'), ('r', 'rain'), ('t', 'temperature'), ('wd', 'wind_direction'), ('ws', 'wind_strength'), ('s', 'snow')], default='unknown', max_length=100)),
                ('value', models.CharField(default='N/A', max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('station_id', models.IntegerField(default=-1)),
            ],
        ),
    ]
